Updated Readme to 3.0.0-4
vrumger/new-i18n pull request #6
Opened 2021-05-05 07:34 UTC by BolverBlitz

2021-05-05 07:35 UTC, BolverBlitz commented
You also want to update your [Gist](https://gist.github.com/AndrewLaneX/618298c5ef179eebc511ca8c8a82eb76)
```js
const { default: newi18n } = require('new-i18n')
const i18n = new newi18n(__dirname, ["en","pt"], "en");

console.log('English:', i18n.translate('en', 'hello_world'));
console.log('Portuguese:', i18n.translate('pt', 'hello_world'));

console.log(i18n.translate('en', 'hi', { name: '...' }));
console.log(i18n.translate('pt', 'hi', { name: '...' }));

i18n.update('en', { hi: 'Hello my name is {{name}}!' });
i18n.update('pt', { hi: 'Olá meu nome é {{name}}!' });

console.log(i18n.translate('en', 'hi', { name: '...' }));
console.log(i18n.translate('pt', 'hi', { name: '...' }));

console.log(`newi18n languages: ${i18n.languages}`)
```

2021-05-06 02:53 UTC, AndrewLaneX requested changes

2021-05-06 02:53 UTC, AndrewLaneX commented on README.md
> +const i18n = new newi18n(__dirname, ["en","pt"], "en");
```suggestion
const { default: I18n } = require('new-i18n');
const i18n = new I18n(__dirname, ['en', 'pt'], 'en');
```

2021-05-06 02:53 UTC, AndrewLaneX commented on README.md
> +console.log(`newi18n languages: ${i18n.languages}`)
```suggestion
console.log(`I18n languages: ${i18n.languages}`);
```

2021-05-09 02:05 UTC, AndrewLaneX requested changes

2021-05-09 02:05 UTC, AndrewLaneX commented on README.md
> +i18n.translate('en', 'hi', { name: '...' }); // 'Hello ...!'
```suggestion
i18n.translate('en', 'hi', { name: '...' }); // 'Hello my name is ...!'
```

2021-05-16 06:06 UTC, AndrewLaneX commented
Sorry about the delay.

2021-05-16 06:06 UTC, merged